language: generic

matrix:
  fast_finish: true
  include:
    - os: linux
      env: PYTHON_VERSION="3.5"
    - os: linux
      env: PYTHON_VERSION="3.6"
    - os: linux
      env: PYTHON_VERSION="3.7"
    - os: linux
      env: PYTHON_VERSION="3.8"
    - os: osx
      env: PYTHON_VERSION="3.5"
    - os: osx
      env: PYTHON_VERSION="3.6"
    - os: osx
      env: PYTHON_VERSION="3.7"
    - os: osx
      env: PYTHON_VERSION="3.8"

before_install:
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
        curl -o miniconda.sh https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh;
    else
        curl -o miniconda.sh https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-x86_64.sh;
    fi
  - bash miniconda.sh -b -p ${HOME}/miniconda
  - source "${HOME}/miniconda/etc/profile.d/conda.sh"
  - conda config --set always_yes yes --set changeps1 no
  - conda config --add channels conda-forge
  - travis_retry conda update --quiet --yes conda
  - conda info --all

install:
  # create a conda environment including our requirements
  - travis_retry conda create --quiet --name ci python=${PYTHON_VERSION} pip setuptools
  - travis_retry conda activate ci
  # install this version
  - python -m pip install .
  # install test requirements
  - travis_retry conda install --quiet --yes --update-deps --name ci --file requirements.txt
  # print package info
  - conda list

script:
  - python -m pytest -rs --verbose --cov gwosc --pyargs gwosc

after_success:
  - travis_retry conda install --quiet --yes --name ci codecov
  - python -m coverage report
  - python -m codecov --flags $(uname) python${PYTHON_VERSION/./}

before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log
cache:
  pip: true
